##第一个单元测试
一个单元测试仅仅只是一段代码，与逻辑代码不同的是，他是用来测试逻辑代码的，并且能检测出逻辑代码的正确与否。

为了检测逻辑代码的正确性，我们将要使用断言。断言用来判断我们的逻辑表达式是否为真，如果为真则正确，如果为否，则错误。正如下面的代码

```
public void assertTrue(boolean condition){
  if(!condition){
    abort();
  }
}
```

我们可以用断言来检测所有的逻辑；就连数字是否相等也可以
```
int a= 2;
assertTrue(a == 2);
```
如果a不等于2，那么程序就会终止。

为了简化数字相等的判断，我们可以调用这样的断言:
```
public void assertEqual(int a,int b){
  assertTrue(a == b);
}
```

好了，有了上面的两种断言模式，我们就可以开始我们的测试。

##测试计划
我们以一个简单的例子开始，一个用来找到一组数中最大数的静态函数为例子
```
int Largest.largest(int[] list);
```

如果我们传递整形数组给这个函数，例如[7,8,9]，这个函数会返回9。这是一种测试方式，但是想想是否还有其他的测试方式。
1：不管这个数组以任何的方式排序，得到的结果应该是一样的
[7,8,9]=>9
[8,7,9]=>9
[9,8,7]=>9
2：如果最大的数字出现两次
[7,8,9,9]=>9   因为我们使用的int类型，而不是Integer类，所以不必关心返回的是第几个
3：如果只有一个水呢
[1]=>1
4：如果参数是负数
[-9,-8,-7]=>7

考虑了所有的情况，那么我们先来实现这个求最大值得函数，
```
public class Largest{
  public static int largest(int[] list){
    int index,max=Integer.MAX_VALUE;
    for(index = 0;index < list.length - 1;index++){
      if(list[index] > max){
        max = list[index];
      }
    }
    return max;
  }
}
```
因为我们已经有了测试的计划，现在我们开始写测试代码，去测试我们函数是否严谨。

##测试函数
首先，我们传递最简单的数组给这个函数
```

import junit.frameword.*;

public class TestLargest extends TestCase{
  public TestLargest(String name){
    super(name);
  }
  public void testSimple(){
    assertEqual(9,Largest.largest[new int[]{7,8,9}]);  
  }
}

```
测试上面的代码，我们得到这样的提示
```
There was 1 failure:
1) testSimple(TestLargest)junit.frameword.AssertFailureError:
  expected 9 but as 2147483647
  as TestLargest.testSimple(TestLargest.java:11)
```

根据提示，我们可以明白，莫名的2147483647是因为我们在初始化max变量的时候，将Integer.MAX_VALUE赋予了它，现在我们调整为0；那么就ok了。

下面我们根据我们的测试计划继续测试：
```
import junit.frameword.*;

public class TestLargest extends TestCase{
  public TestLargest(String name){
    super(name);
  }
  
  public void testSimple(){
    assertEquals(9,Largest.largest(new int[]{7,8,9}));
  }
  
  public void testOrder(){
    assertEquals(9,Largest.largest(new int[]{9,8,7}));
    assertEquals(9,Largest.largest(new int[]{8,9,7}));
    assertEquals(9,Largest.largest(new int[]{7,9,8}));
  }
}

```

我们让程序跑一会，发现给出了这样的额提示：
```
There was 1 failure:
1)testOrder(TestLargest)junit.framework.AssertionFailedError:expected:9 but was 8
  at TestLargest.testOrder(TestLargest.java : 10)
```

为什么得到的最大数是8呢，是不是代码忽略了最后一个数，或者说在检测最后一个数之前，程序以及函数已经终止了。
我们的代码是
  for(index=0;index < list.length - 1;index ++){
但是正确的写法是
  1：for(index=0;index<list.length;index++){
  2:  for(index=0;index<= list.length-1;index++){

两种都可以，但是第一种更加容易读懂。
通过了不同顺序的测试，我们接着进行下一个测试，最大数出现两次:
```
  public void testDups(){
    assertEquals(9, Largest.largest( new int[]{9,8,9,7} ));
  }
```
运行代码测试通过，接着测试只有一个数字的情况
```
public void testOne(){
  assertEquals(1,Largest.largest(new int[]{1}));
}
```
运行代码，测试ok，继续我们的测试，如果数组中都是负数呢
```
public void testNegative(){
  assertEquals(-7,Largest.largest(new int[]{-7,-8,-9}));
}
```
运行代码，我们得到这样的提示:
```
There was 1 failure:
1)testOrder(TestLargest)junit.framework.AssertionFailedError:expected:-7 but was 0
  at TestLargest.testOrder(TestLargest.java : 10)
```
为什么没有得到-7而是得到了0呢，我们看代码，原来是我们在前面将0赋予了max；我们修改代码将MIN_VALUE赋予它，再次测试，
完美运行；

等等，如果我们传递给Largest.largest函数的参数是空呢，变量是空，或者数组长度是0呢；我们也应该考虑，因为无法保证调用者在调用的是一定能保证传递的数据是非空的。所以说，我们要添加检测一些代码，以检测如果遇到这样的情况，我们要跑出异常
```
public static int largest(int[] list){
  if(list.length == 0){
    throw new RuntimeException("Empty list");  
  }
  ...
}
```
虽然这种情况发生的几率很小，但是我们还是需要添加代码，检测是否在传入长度为0的数组时候，能否检测到异常；
```
public void testEmpty(){
  try{
    Largest.largest(new int[]{});
    fail("Should have throw an exception");
  }
  catch(RuntimeException e){
    assert(True);
  }
}
```
最后提醒大家，所有的测试代码和逻辑代码，都应该干净简单。测试代码尤其要简洁，即便是压力测试代码。


